# Generated by Django 4.1.1 on 2022-09-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newboss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
            ],
        ),
        migrations.DeleteModel(
            name='Newboss',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
