# Generated by Django 4.1.1 on 2022-09-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_delete_newboss_delete_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailcollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=122)),
            ],
        ),
    ]
