# Generated by Django 4.1.1 on 2022-09-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_emailcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
