# Generated by Django 4.1.1 on 2022-09-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_catorgry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('desc', models.CharField(max_length=122)),
                ('prize', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='static/uploadingimg')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
