# Generated by Django 4.1.1 on 2022-09-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_adminproduct_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminproduct',
            name='catorgry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.catorgry'),
        ),
    ]
