# Generated by Django 4.1.1 on 2022-09-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_adminproduct_catorgry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminproduct',
            name='catorgry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.catorgry'),
        ),
    ]
